name        'magento2'
maintainer  'Inviqa'
license     'Apache 2.0'
description 'Magento2 specific cookbook'
version     '1.1.0'

depends 'chef-varnish'
depends 'config-driven-helper'
depends 'rbenv'
depends 'cron', '~> 1.4.0'
depends 'nginx'
depends 'hostsfile', '~> 2.4.6'
depends 'nodejs'
